spring:
  application:
    name: proxy

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    service1:
      path: /service1/
      serviceId: service1
    service2:
      path: /service2/
      serviceId: service2

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG